version: 1.0.0.{build}
image: Visual Studio 2017
cache:
  # Node Modules
  - '%APPDATA%\npm-cache'
  - '**\node_modules'
  # Nuget
  - '%USERPROFILE%\.nuget\packages'
install:
  - ps: Install-Product node 9
  - ps: node --version
  - ps: npm --version
build_script:
  - ps: cd ./src/
  - ps: dotnet restore
  - ps: dotnet build
test_script:
  - ps: cd ../test/
  - ps: dotnet restore
  - ps: dotnet xunit