language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
 - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
 - sudo apt-get install --only-upgrade nodejs
script:
 - node --version
 - npm --version
 - cd ./src/
 - dotnet restore
 - dotnet build
 - cd ../test/
 - dotnet restore
 - dotnet xunit