language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore ./src/Fallback.AspNetCore.csproj
 - dotnet build ./src/Fallback.AspNetCore.csproj
 - dotnet restore ./test/Fallback.AspNetCore.Test.csproj
 - dotnet xunit ./test/Fallback.AspNetCore.Test.csproj